from __future__ import annotations

import argparse
from pathlib import Path
import sys

import matplotlib
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# Use non-interactive backend for CLI environments.
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build daily execution monitoring dashboard (CSV + PNG) from rebalance history."
    )
    parser.add_argument(
        "--history-csv",
        type=Path,
        default=Path("outputs/execution/rebalance_history.csv"),
        help="History CSV generated by scripts/17_execution_history.py.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path("outputs/execution/dashboard_daily.csv"),
        help="Daily monitoring table output path.",
    )
    parser.add_argument(
        "--output-png",
        type=Path,
        default=Path("outputs/execution/dashboard_daily.png"),
        help="Dashboard chart output path.",
    )
    return parser.parse_args()


def _resolve_path(path: Path) -> Path:
    if path.is_absolute():
        return path
    return (PROJECT_ROOT / path).resolve()


def _load_history(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing history CSV: {path}. Run scripts/17_execution_history.py first."
        )
    df = pd.read_csv(path)
    required_cols = {
        "timestamp_utc",
        "account_equity_pre",
        "pre_cash_fraction",
        "estimated_cash_after_fraction",
        "target_weight_gross",
        "investable_target_fraction",
        "target_under_investment_fraction",
        "n_orders",
        "apply",
    }
    missing = sorted(required_cols - set(df.columns))
    if missing:
        raise ValueError(f"History CSV missing required columns: {missing}")
    return df


def _build_daily_table(history_df: pd.DataFrame) -> pd.DataFrame:
    df = history_df.copy()
    df["timestamp_utc"] = pd.to_datetime(df["timestamp_utc"], utc=True, errors="coerce")
    df = df.dropna(subset=["timestamp_utc"]).sort_values("timestamp_utc").reset_index(drop=True)
    if df.empty:
        raise ValueError("History CSV has no valid timestamp rows.")

    for col in [
        "account_equity_pre",
        "pre_cash_fraction",
        "estimated_cash_after_fraction",
        "target_weight_gross",
        "investable_target_fraction",
        "target_under_investment_fraction",
        "n_orders",
    ]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    df["apply"] = df["apply"].astype(str).str.lower().isin({"true", "1", "yes", "y"})
    df["run_date"] = df["timestamp_utc"].dt.date
    daily = (
        df.sort_values("timestamp_utc")
        .groupby("run_date", as_index=False)
        .tail(1)
        .sort_values("timestamp_utc")
        .reset_index(drop=True)
    )

    first_equity = float(daily["account_equity_pre"].dropna().iloc[0])
    daily["equity_index"] = daily["account_equity_pre"] / first_equity
    daily["cash_pre_pct"] = 100.0 * daily["pre_cash_fraction"]
    daily["cash_after_orders_pct"] = 100.0 * daily["estimated_cash_after_fraction"]
    daily["target_gross_pct"] = 100.0 * daily["target_weight_gross"]
    daily["investable_target_pct"] = 100.0 * daily["investable_target_fraction"]
    daily["target_under_investment_pct"] = 100.0 * daily["target_under_investment_fraction"]
    daily["apply_int"] = daily["apply"].astype(int)

    ordered_cols = [
        "run_date",
        "timestamp_utc",
        "apply",
        "n_orders",
        "account_equity_pre",
        "equity_index",
        "cash_pre_pct",
        "cash_after_orders_pct",
        "target_gross_pct",
        "investable_target_pct",
        "target_under_investment_pct",
    ]
    return daily[ordered_cols].copy()


def _plot_dashboard(daily_df: pd.DataFrame, output_png: Path) -> None:
    dates = pd.to_datetime(daily_df["run_date"], utc=False)

    fig, axes = plt.subplots(2, 1, figsize=(12, 8), sharex=True)

    ax0 = axes[0]
    ax0.plot(dates, daily_df["account_equity_pre"], color="#1f77b4", marker="o", label="Equity pre-rebalance")
    ax0.set_ylabel("Equity (USD)")
    ax0.grid(alpha=0.25)

    ax0b = ax0.twinx()
    ax0b.plot(dates, daily_df["equity_index"], color="#2ca02c", linestyle="--", marker="x", label="Equity index")
    ax0b.set_ylabel("Equity Index (start=1.0)")

    lines_0, labels_0 = ax0.get_legend_handles_labels()
    lines_0b, labels_0b = ax0b.get_legend_handles_labels()
    ax0.legend(lines_0 + lines_0b, labels_0 + labels_0b, loc="best")
    ax0.set_title("Execution Monitoring Dashboard")

    ax1 = axes[1]
    ax1.plot(dates, daily_df["target_gross_pct"], color="#ff7f0e", marker="o", label="Target gross %")
    ax1.plot(
        dates,
        daily_df["investable_target_pct"],
        color="#7f7f7f",
        linestyle="--",
        marker=".",
        label="Investable target %",
    )
    ax1.plot(dates, daily_df["cash_pre_pct"], color="#d62728", marker="s", label="Cash pre %")
    ax1.plot(
        dates,
        daily_df["cash_after_orders_pct"],
        color="#9467bd",
        marker="^",
        label="Cash after orders % (est)",
    )
    ax1.set_ylabel("Exposure / Cash (%)")
    ax1.set_xlabel("Run Date")
    ax1.grid(alpha=0.25)
    ax1.legend(loc="best")

    fig.autofmt_xdate()
    fig.tight_layout()
    output_png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_png, dpi=160)
    plt.close(fig)


def main() -> None:
    args = parse_args()

    history_csv = _resolve_path(args.history_csv)
    output_csv = _resolve_path(args.output_csv)
    output_png = _resolve_path(args.output_png)

    history_df = _load_history(history_csv)
    daily_df = _build_daily_table(history_df)

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    daily_df.to_csv(output_csv, index=False)
    _plot_dashboard(daily_df=daily_df, output_png=output_png)

    latest = daily_df.iloc[-1]
    print("Execution dashboard generated")
    print(f"Daily rows: {len(daily_df)}")
    print(f"Daily CSV: {output_csv}")
    print(f"Dashboard PNG: {output_png}")
    print(f"Latest date: {latest['run_date']}")
    print(f"Latest equity: {float(latest['account_equity_pre']):.2f}")
    print(f"Latest target gross %: {float(latest['target_gross_pct']):.2f}")
    print(f"Latest cash pre %: {float(latest['cash_pre_pct']):.2f}")


if __name__ == "__main__":
    main()
