from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from dotenv import load_dotenv

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.data import load_yaml


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check IBKR order status using IDs from latest rebalance summary or manual input."
    )
    parser.add_argument("--config-execution", type=Path, default=Path("configs/config_execution.yaml"))
    parser.add_argument(
        "--summary",
        type=Path,
        default=Path("outputs/execution/rebalance_latest_summary.json"),
        help="Summary JSON generated by scripts/04_rebalance.py.",
    )
    parser.add_argument(
        "--order-ids",
        type=str,
        default="",
        help="Comma-separated IBKR order IDs. If omitted, uses broker_order_ids from --summary.",
    )
    parser.add_argument(
        "--include-all-open",
        action="store_true",
        help="Also include open IBKR orders not present in target IDs.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("outputs/execution/ibkr_orders_latest.json"),
        help="JSON output path for the order status report.",
    )
    parser.add_argument("--host", type=str, default=None, help="Override IBKR host from config.")
    parser.add_argument("--port", type=int, default=None, help="Override IBKR port from config.")
    parser.add_argument("--client-id", type=int, default=None, help="Override IBKR client_id from config.")
    parser.add_argument("--account", type=str, default=None, help="Override IBKR account from config.")
    return parser.parse_args()


def _resolve_env(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {k: _resolve_env(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_resolve_env(v) for v in obj]
    if isinstance(obj, str) and obj.startswith("${") and obj.endswith("}"):
        var = obj[2:-1]
        return os.getenv(var)
    return obj


def _parse_order_ids(raw: str) -> list[int]:
    if not raw.strip():
        return []
    ids: list[int] = []
    seen: set[int] = set()
    for token in raw.split(","):
        value = token.strip()
        if not value:
            continue
        try:
            parsed = int(value)
        except ValueError as exc:
            raise ValueError(f"Invalid order id {value!r}. Use comma-separated integers.") from exc
        if parsed <= 0:
            raise ValueError(f"Order IDs must be positive integers. Got: {parsed}")
        if parsed not in seen:
            seen.add(parsed)
            ids.append(parsed)
    return ids


def _load_summary_order_ids(path: Path) -> tuple[list[int], dict[str, Any]]:
    summary = json.loads(path.read_text(encoding="utf-8"))
    raw_ids = summary.get("broker_order_ids", [])
    if not isinstance(raw_ids, list):
        raise ValueError("Invalid summary: `broker_order_ids` must be a list.")

    parsed: list[int] = []
    seen: set[int] = set()
    for raw in raw_ids:
        order_id = int(raw)
        if order_id <= 0:
            continue
        if order_id not in seen:
            seen.add(order_id)
            parsed.append(order_id)
    return parsed, summary


def _matches_account(expected: str | None, candidate: str | None) -> bool:
    if not expected:
        return True
    if candidate in {None, ""}:
        return True
    return str(candidate).strip() == str(expected).strip()


def _trade_payload(trade: Any) -> dict[str, Any]:
    order = getattr(trade, "order", None)
    status = getattr(trade, "orderStatus", None)
    contract = getattr(trade, "contract", None)
    return {
        "order_id": int(getattr(order, "orderId", 0) or 0),
        "symbol": str(getattr(contract, "symbol", "") or ""),
        "action": str(getattr(order, "action", "") or ""),
        "total_qty": float(getattr(order, "totalQuantity", 0.0) or 0.0),
        "filled_qty": float(getattr(status, "filled", 0.0) or 0.0),
        "remaining_qty": float(getattr(status, "remaining", 0.0) or 0.0),
        "avg_fill_price": float(getattr(status, "avgFillPrice", 0.0) or 0.0),
        "status": str(getattr(status, "status", "") or ""),
        "order_type": str(getattr(order, "orderType", "") or ""),
        "limit_price": (
            float(getattr(order, "lmtPrice", 0.0) or 0.0)
            if str(getattr(order, "orderType", "") or "").upper() == "LMT"
            else None
        ),
        "tif": str(getattr(order, "tif", "") or ""),
        "account": str(getattr(order, "account", "") or ""),
    }


def _execution_payload(execution: Any) -> dict[str, Any]:
    exec_obj = getattr(execution, "execution", None)
    contract = getattr(execution, "contract", None)
    return {
        "order_id": int(getattr(exec_obj, "orderId", 0) or 0),
        "symbol": str(getattr(contract, "symbol", "") or ""),
        "side": str(getattr(exec_obj, "side", "") or ""),
        "shares": float(getattr(exec_obj, "shares", 0.0) or 0.0),
        "price": float(getattr(exec_obj, "price", 0.0) or 0.0),
        "time": str(getattr(exec_obj, "time", "") or ""),
        "account": str(getattr(exec_obj, "acctNumber", "") or ""),
    }


def _merge_order_rows(
    target_ids: list[int],
    open_by_id: dict[int, dict[str, Any]],
    completed_by_id: dict[int, dict[str, Any]],
    execution_by_id: dict[int, list[dict[str, Any]]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for order_id in target_ids:
        open_row = open_by_id.get(order_id)
        completed_row = completed_by_id.get(order_id)
        executions = execution_by_id.get(order_id, [])

        execution_shares = float(sum(abs(item["shares"]) for item in executions))
        execution_notional = float(sum(abs(item["shares"]) * item["price"] for item in executions))
        execution_avg_price = float(execution_notional / execution_shares) if execution_shares > 0 else 0.0

        symbol = ""
        action = ""
        total_qty = 0.0
        filled_qty = 0.0
        remaining_qty = 0.0
        avg_fill_price = 0.0
        status = ""
        source = "unknown"

        if open_row is not None:
            symbol = open_row["symbol"]
            action = open_row["action"]
            total_qty = float(open_row["total_qty"])
            filled_qty = float(open_row["filled_qty"])
            remaining_qty = float(open_row["remaining_qty"])
            avg_fill_price = float(open_row["avg_fill_price"])
            status = str(open_row["status"])
            source = "open"
        elif completed_row is not None:
            symbol = completed_row["symbol"]
            action = completed_row["action"]
            total_qty = float(completed_row["total_qty"])
            filled_qty = float(completed_row["filled_qty"])
            remaining_qty = float(completed_row["remaining_qty"])
            avg_fill_price = float(completed_row["avg_fill_price"])
            status = str(completed_row["status"])
            source = "completed"
        elif executions:
            last_execution = executions[-1]
            symbol = str(last_execution["symbol"])
            action = str(last_execution["side"])
            total_qty = float(execution_shares)
            filled_qty = float(execution_shares)
            remaining_qty = 0.0
            avg_fill_price = float(execution_avg_price)
            status = "ExecutionFound"
            source = "executions_only"

        if executions and filled_qty <= 0:
            filled_qty = execution_shares
        if executions and avg_fill_price <= 0:
            avg_fill_price = execution_avg_price

        rows.append(
            {
                "order_id": int(order_id),
                "source": source,
                "status": status,
                "symbol": symbol,
                "action": action,
                "total_qty": float(total_qty),
                "filled_qty": float(filled_qty),
                "remaining_qty": float(remaining_qty),
                "avg_fill_price": float(avg_fill_price),
                "executions_count": int(len(executions)),
                "execution_filled_qty": float(execution_shares),
                "execution_avg_price": float(execution_avg_price),
                "last_execution_time": str(executions[-1]["time"]) if executions else "",
            }
        )
    return rows


def main() -> None:
    args = parse_args()
    load_dotenv(dotenv_path=(PROJECT_ROOT / ".env"), override=False)

    config_execution = _resolve_env(load_yaml(args.config_execution.resolve()))
    ibkr_cfg = config_execution.get("ibkr", {})

    host = str(args.host or ibkr_cfg.get("host") or "127.0.0.1")
    port = int(args.port or ibkr_cfg.get("port") or 7497)
    client_id = int(args.client_id or ibkr_cfg.get("client_id") or 101)
    account = str(args.account or ibkr_cfg.get("account") or "")
    readonly = bool(ibkr_cfg.get("readonly"))

    summary_path = args.summary if args.summary.is_absolute() else (PROJECT_ROOT / args.summary).resolve()
    summary_payload: dict[str, Any] | None = None
    order_ids = _parse_order_ids(args.order_ids)
    if not order_ids:
        if not summary_path.exists():
            raise FileNotFoundError(
                f"No manual --order-ids and missing summary file: {summary_path}. "
                "Run scripts/04_rebalance.py --apply or pass --order-ids."
            )
        order_ids, summary_payload = _load_summary_order_ids(summary_path)

    if not order_ids and not args.include_all_open:
        raise ValueError("No order IDs to check. Pass --order-ids or --include-all-open.")

    try:
        from ib_insync import IB
    except Exception as exc:
        raise RuntimeError("ib_insync is required for IBKR order checks.") from exc

    ib = IB()
    try:
        ib.connect(host=host, port=port, clientId=client_id, timeout=10)
    except Exception as exc:
        raise SystemExit(
            "Could not connect to IBKR API. "
            f"host={host} port={port} client_id={client_id}. "
            f"Original error: {exc}"
        ) from exc
    try:
        ib.reqAllOpenOrders()
        ib.sleep(0.5)
        open_trades = ib.openTrades()
        executions = ib.reqExecutions()

        try:
            completed_orders = ib.reqCompletedOrders(apiOnly=False)
        except Exception:
            completed_orders = []

        try:
            positions = ib.positions(account=account or "")
        except TypeError:
            positions = ib.positions()
    finally:
        ib.disconnect()

    open_by_id: dict[int, dict[str, Any]] = {}
    for trade in open_trades:
        payload = _trade_payload(trade)
        order_id = int(payload["order_id"])
        if order_id <= 0:
            continue
        if not _matches_account(account, payload.get("account")):
            continue
        open_by_id[order_id] = payload

    completed_by_id: dict[int, dict[str, Any]] = {}
    for trade in completed_orders:
        payload = _trade_payload(trade)
        order_id = int(payload["order_id"])
        if order_id <= 0:
            continue
        if not _matches_account(account, payload.get("account")):
            continue
        completed_by_id[order_id] = payload

    execution_by_id: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for execution in executions:
        payload = _execution_payload(execution)
        order_id = int(payload["order_id"])
        if order_id <= 0:
            continue
        if not _matches_account(account, payload.get("account")):
            continue
        execution_by_id[order_id].append(payload)

    target_ids = list(order_ids)
    if args.include_all_open:
        for order_id in sorted(open_by_id):
            if order_id not in target_ids:
                target_ids.append(order_id)

    order_rows = _merge_order_rows(
        target_ids=target_ids,
        open_by_id=open_by_id,
        completed_by_id=completed_by_id,
        execution_by_id=execution_by_id,
    )
    order_rows = sorted(order_rows, key=lambda row: int(row["order_id"]))
    status_counts = Counter(str(row["status"] or "UNKNOWN") for row in order_rows)
    source_counts = Counter(str(row["source"]) for row in order_rows)

    nonzero_positions = sorted(
        (
            {
                "symbol": str(pos.contract.symbol),
                "quantity": float(pos.position),
                "avg_cost": float(pos.avgCost),
            }
            for pos in positions
            if abs(float(pos.position)) > 0
        ),
        key=lambda row: row["symbol"],
    )

    output_path = args.output if args.output.is_absolute() else (PROJECT_ROOT / args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    report = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "status": "ok",
        "host": host,
        "port": port,
        "client_id": client_id,
        "account": account,
        "readonly": readonly,
        "summary_path": str(summary_path),
        "summary_apply": summary_payload.get("apply") if isinstance(summary_payload, dict) else None,
        "summary_rebalance_date": summary_payload.get("rebalance_date") if isinstance(summary_payload, dict) else None,
        "target_order_ids_count": int(len(target_ids)),
        "all_open_orders_count": int(len(open_by_id)),
        "executions_total_count": int(sum(len(v) for v in execution_by_id.values())),
        "status_counts": dict(sorted(status_counts.items(), key=lambda item: item[0])),
        "source_counts": dict(sorted(source_counts.items(), key=lambda item: item[0])),
        "orders": order_rows,
        "positions_nonzero_count": int(len(nonzero_positions)),
        "positions_nonzero": nonzero_positions,
    }
    output_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")

    print("IBKR order check completed")
    print(f"Endpoint: {host}:{port} (client_id={client_id})")
    print(f"Account: {account or '<auto>'}")
    print(f"Target order IDs: {len(target_ids)}")
    print(f"Open orders (account filter): {len(open_by_id)}")
    print(f"Executions found: {sum(len(v) for v in execution_by_id.values())}")
    print(f"Positions non-zero: {len(nonzero_positions)}")
    print(f"Status counts: {dict(sorted(status_counts.items(), key=lambda item: item[0]))}")
    print(f"Source counts: {dict(sorted(source_counts.items(), key=lambda item: item[0]))}")
    print(f"Report: {output_path}")

    if order_rows:
        print("Order details:")
        for row in order_rows:
            print(
                f"  - {int(row['order_id'])}: {row['status'] or 'UNKNOWN'} "
                f"[{row['source']}] {row['symbol']} {row['action']} "
                f"filled={row['filled_qty']}/{row['total_qty']} "
                f"remaining={row['remaining_qty']} execs={row['executions_count']}"
            )


if __name__ == "__main__":
    main()
